#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d " 1 " " 2 " " 3 " " 4 " " 5 " " 6 " " 7 " " 8 " " 9 " " 0 "

exec ~/.config/bspwm/autostart.sh

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#404040"
bspc config focused_border_color "#fefefef"

