# CONFIG #

#shell = { program = "$SHELL", args = [""] }
#working_directory = "~"
#live_config_reload = true

[window]
dimensions = { columns = 90, lines = 40 }
position = "None"
padding = { x = 15, y = 15 }
dynamic_padding = false
decorations = "Full"
opacity = 0.90
blur = false
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = false
class = { instance = "Alacritty", general = "Alacritty" }
decorations_theme_variant = "None"
resize_increments = false

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "firacode", style = "Regular" }
bold = { family = "firacode", style = "Bold" }
italic = { family = "firacode", style = "Italic" }
bold_italic = { family = "firacode", style = "Bold Italic" }
size = 10
offset = { x = 0, y = 0 }
builtin_box_drawing = true

[colors]
cursor = { text = "CellBackground", cursor = "CellForeground" }
vi_mode_cursor = { text = "CellBackground", cursor = "CellForeground" }
line_indicator = { foreground = "None", background = "None" }
footer_bar = { foreground = "#181818", background = "#d8d8d8" }
selection = { text = "CellBackground", background = "CellForeground" }
indexed_colors = []
transparent_background_colors = false
draw_bold_text_with_bright_colors = false

[colors.primary]
foreground = "#ffffff"
background = "#121212"
dim_foreground = "#828482"
bright_foreground = "None"

[colors.search]
matches = { foreground = "#181818", background = "#ac4242" }
focused_match = {foreground = "#181818", background = "#f4bf75" }

[colors.hints]
start = { foreground = "#181818", background = "#f4bf75" }
end = { foreground = "#181818", background = "#ac4242" }

[colors.normal]
black   = "#282a2e"
red     = "#c5300c"
green   = "#c1dd18"
yellow  = "#d5d5d5"
blue    = "#d5d5d5"
magenta = "#d5d5d5"
cyan    = "#d5d5d5"
white   = "#707880"

[colors.bright]
black   = "#373b41"
red     = "#df6a6a"
green   = "#dcf354"
yellow  = "#d5d5d5"
blue    = "#d5d5d5"
magenta = "#d5d5d5"
cyan    = "#d5d5d5"
white   = "#ffffff"

[bell]
animation = "EaseOutQuad"
duration = 250
color = "#161616"
command = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = false

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = "None"
blink_interval = 750
blink_timeout = 0
unfocused_hollow = false
thickness = 0.15

[terminal]
osc52 = "OnlyCopy"

[mouse]
hide_when_typing = false
bindings = []

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
renderer = "None"
print_events = false
highlight_damage = false
prefer_egl = false
